### ISSUE TITLE
Incorrect version generation if they contain leading zeros

### ISSUE THREAD

**Issue by NullPiotrException** [tim-lebedkov/npackd-cpp#15]
If a version number contains a leading zero in any of the parts, it will be stripped when generating a version for a package.

E.g. the newest version of 7-Zip is 18.05 but the generated package version is 18.5. It is confusing and will be even more when/if actual version 18.5 comes.

**Comment by tim-lebedkov** [comment]
All versions can only contain numbers and are normalized. The numbers are parsed. This way it is easy to define which version is newer. 

In your example 18.05 becomes 18.5 and it is older than 18.50 (18.50 > 18.05). Note that if 7-zip developers are consistent, they would name the new version 18.50 and not 18.5. This would work well with Npackd.

**Comment by NullPiotrException** [comment]
Yes, you're correct that 7-zip will have a version 18.50 and not 18.5 but I think there might be problem with normalizing version numbers instead of treating them like strings. I just wanted to make an issue here so there's a place to discuss this.

Closing since I can't provide any proof that normalizing will be a problem.
