### ISSUE TITLE
Switching from SHA1 to SHA512

### ISSUE THREAD

**Issue by NullPiotrException** [tim-lebedkov/npackd-cpp#16]
It's nice that 2 options for checksums are provided but SHA1 is [no longer safe](https://en.wikipedia.org/wiki/SHA-1#SHAttered_%E2%80%93_first_public_collision).
It would be cool if users haved the chance of checking SHA512 instead.

**Comment by tim-lebedkov** [comment]
Do you have any examples of packages that use SHA512?

**Comment by NullPiotrException** [comment]
Out of all 100 packages from #14, only these provide SHA512. There might be some packages that I didn't check and provide SHA512 but I don't think there are many more of them.
```
Gimp
VeraCrypt
Putty
Zenmap
Ant
Arduino
Cyberfox
Cyberfox 64 bit
FileZilla Client
FileZilla Client 64 bit
Gparted
Ghostscript
Ghostscript 64 bit
JMeter
Open Connect
SyncTrayzor
SyncTrayzor 64 bit
Tomcat
Tomcat 64 bit
```

**Comment by tim-lebedkov** [comment]
Some packages mentioned in your previous post now also provide SHA-256, which seems to be a more widely used hash sum. A notable exception is the software from Apache. SHA-256 is in my opinion enough for the foreseeable future. It is supported by Npackd right now.

Gimp: https://www.gimp.org/downloads/
VeraCrypt: https://launchpadlibrarian.net/388150962/veracrypt-1.23-sha256sum.txt
Putty: https://the.earth.li/~sgtatham/putty/0.70/sha256sums
Zenmap: https://nmap.org/dist/sigs/nmap-7.70.dmg.digest.txt
Ant: SHA-512
Arduino: only a GPG signature
Cyberfox: have not found any hash sums
FileZilla Client: only SHA-512
Gparted: https://gparted.org/gparted-live/stable/CHECKSUMS.TXT
Ghostscript: only SHA-512
JMeter: only SHA-512
Open Connect: only SHA-512
SyncTrayzor: only SHA-512
Tomcat: only SHA-512

**Comment by NullPiotrException** [comment]
I understand. Was worth trying.

As for Cyberfox they only provide SHA512 here:
https://sourceforge.net/projects/cyberfox/files

Arduino only provides MD5 and SHA512:
https://downloads.arduino.cc/arduino-1.8.8.md5sum.txt
https://downloads.arduino.cc/arduino-1.8.8.sha512sum.txt

I will contact both of them and ask for SHA256 as well.
