### ISSUE TITLE
Generating SHA256 returning different sums

### ISSUE THREAD

**Issue by NullPiotrException** [tim-lebedkov/npackd-cpp#18]
In [LibreOffice 64bit](https://www.npackd.org/p/libreoffice64/6.0.5) when I click "Compute SHA-256" it returns a different sum each time. It also happens very fast so it probably doesn't download the file at all.
Maybe it fails downloading the file and gets a different part of the file each time. But the problem is that the maintainer doesn't know about it because there's no error. So imo if the file fails to be downloaded there should be an error like "Did not compute SHA256 due to failure of downloading the file".

**Comment by tim-lebedkov** [comment]
The download did not fail. It just downloaded the page for donations: https://www.libreoffice.org/donate/dl/win-x86_64/6.0.5/en-US/LibreOffice_6.0.5_Win_x64.msi

The new package version was still labeled as "untested" and would not appear in the default repositories.

I fixed the package. The new version will appear in the default repository tomorrow.

**Comment by NullPiotrException** [comment]
Whoops. My bad. I picked the wrong discovery package download URL pattern. Sorry.
Would you mind it if I changed `https://artfiles.org/documentfoundation.org/libreoffice/stable/${v0}.${v1}.${v2}/win/x86_64/LibreOffice_${v0}.${v1}.${v2}_Win_x64.msi` to `https://download.documentfoundation.org/libreoffice/stable/${v0}.${v1}.${v2}/win/x86_64/LibreOffice_${v0}.${v1}.${v2}_Win_x64.msi`? I think it's better to download the files from official website.
That's what I meaned to do by updating the package pattern.

**Comment by tim-lebedkov** [comment]
No problem.
