### ISSUE TITLE
Feature request: offline archive

### ISSUE THREAD

**Issue by reclaimed** [tim-lebedkov/npackd-cpp#20]
Hello there. Is it possible to use Npackd to create and keep updated an offline collection of distributives? I mean, I have a USB HDD or something and I attach it to the PC and run something like
```
ncl download Firefox
ncl update --offline
```
And to install -  "ncl install Firefox --offline"

Another question was already asked, but more voices better :)  Please add the global checkboxes to select and export the list of packages in a convenient way.

**Comment by tim-lebedkov** [comment]
You can export a repository from the GUI only ("Package"/"Export"). Updating such a repository is not supported. You will have to export everything again. 

It is also possible to use only the repository from your USB drive like this:
`ncl add-repo --url=file:///H:\Rep.xml`

Once you set the repository to H:\Rep.xml, everything is offline.

I actually cannot remember anybody asking for checkboxes.
