### ISSUE TITLE
Update checker

### ISSUE THREAD

**Issue by GoogleCodeExporter** [tim-lebedkov/npackd-cpp#27]
```
I would like to suggest an enhancement for npackd. I am using it for about 1-2 
years. I recently realized that most of the time I am opening it to update all 
my programs.

I might be interesting to create a background scheduled task for an update 
checker. 

1. If one or more of my installed program has a new version then an icon will 
popup in the notification center (like the windows update).

2. When clicking on this icon, it will launch Npackd (maybe launch direct

3. an option will be available to set the schedule period (every hour, day, 
week, month, never)
```

Original issue reported on code.google.com by `julien.p...@gmail.com` on 5 Mar 2013 at 8:46

**Comment by tim-lebedkov** [comment]
this is what we have now:
![Task](https://user-images.githubusercontent.com/831371/64456986-c27a4700-d0f1-11e9-99d0-f682d13ac8f1.png)
![Settings](https://user-images.githubusercontent.com/831371/64456993-c8702800-d0f1-11e9-947b-ebd9163260e5.png)

**Comment by tim-lebedkov** [comment]
Notification and what Npackd shows if you click on it:
![Notification](https://user-images.githubusercontent.com/831371/64457153-2ef54600-d0f2-11e9-8028-b7aa2b8f1acb.png)
![Updates](https://user-images.githubusercontent.com/831371/64457162-33b9fa00-d0f2-11e9-8c48-d954bd9a7046.png)
