### ISSUE TITLE
LibreOffice not updated

### ISSUE THREAD

**Issue by NullPiotrException** [tim-lebedkov/npackd-cpp#3]
My LibreOffice version is 5.3.1.2.
There's now version 5.3.2 but Npackd doesn't realize there's a new version and shows me that there's nothing to update.

**Comment by tim-lebedkov** [comment]
Have you installed LibreOffice without Npackd? If so, Npackd will not be able to update it. This will probably work in the next version (1.23).

If you installed LibreOffice with Npackd, the updates come every 3 months. Some packages are updated by volunteers, but the number is insignificant.

**Comment by NullPiotrException** [comment]
Oh, I see.
I thought I can update programs installed by me because I had 1 app that I could update with Npackd and I installed it myself.
While we're talking, can I do something to help you with updating the versions?

**Comment by tim-lebedkov** [comment]
Sure. Let me know which packages you would like to update and I will add you to the list of editors. I also would need your @gmail.com user name.
