### ISSUE TITLE
Allow to filter the Application list for software without Warning in Description

### ISSUE THREAD

**Issue by Mannshoch** [tim-lebedkov/npackd-cpp#42]
Allow to filter the Application list for software without Warning in Description

**Comment by tim-lebedkov** [comment]
the search for "file manager -warning" will find all file managers without warnings.

**Comment by tim-lebedkov** [comment]
you can test it from here: https://ci.appveyor.com/project/tim-lebedkov/npackd-cpp/build/job/b9k8r81hcfapms8b/artifacts
