### ISSUE TITLE
Warn me if uninstallation isn't 100% successful

### ISSUE THREAD

**Issue by igitur** [tim-lebedkov/npackd-cpp#45]
Hi,

Often during uninstallation or upgrade, the package directory isn't removed fully, due to various reasons (e.g. the shell is holding on to a .dll file).

During upgrade, I would then end up with a duplicate directory, e.g this:
![image](https://user-images.githubusercontent.com/145854/69062486-ab29d500-0a23-11ea-9fdf-e6b841a6cbbd.png)

I'd like the option to try forcefully delete the original directory first so that the new package can be installed in the original directory instead of defaulting to a `_2` version. 

For pure uninstallation, I think a normal message to inform the user is sufficient.

For upgrade, I think the process should be paused and the user should have a choice of either manually deleting the original directory, or there should be an option for NPackd to proceed and attempt to install the newer package in the original directory anywa.

**Comment by tim-lebedkov** [comment]
Here is how it looks in the console: 

![Bildschirmfoto vom 2019-12-01 12-35-48](https://user-images.githubusercontent.com/831371/69913372-271a1900-1437-11ea-8420-b34d47c553ed.png)

**Comment by tim-lebedkov** [comment]
Here is how it looks in the event log:

![Bildschirmfoto vom 2019-12-01 12-37-34](https://user-images.githubusercontent.com/831371/69913384-5f215c00-1437-11ea-9005-5276f076ac66.png)

**Comment by tim-lebedkov** [comment]
Here is how it looks in the UI:

![Bildschirmfoto vom 2019-12-02 19-58-55](https://user-images.githubusercontent.com/831371/69988490-0985a600-1542-11ea-949f-e7d05633776f.png)

**Comment by tim-lebedkov** [comment]
try it from here: https://ci.appveyor.com/project/tim-lebedkov/npackd-cpp/builds/29387092
