### ISSUE TITLE
Deprecated GetVersionEx

### ISSUE THREAD

**Issue by OgreTransporter** [tim-lebedkov/npackd-cpp#47]
https://docs.microsoft.com/en-us/windows/win32/api/sysinfoapi/nf-sysinfoapi-getversionexa

> [GetVersionEx may be altered or unavailable for releases after Windows 8.1. Instead, use the Version Helper functions] 
> 
> With the release of Windows 8.1, the behavior of the GetVersionEx API has changed in the value it will return for the operating system version. The value returned by the GetVersionEx function now depends on how the application is manifested.
> 
> Applications not manifested for Windows 8.1 or Windows 10 will return the Windows 8 OS version value (6.2). Once an application is manifested for a given operating system version, GetVersionEx will always return the version that the application is manifested for in future releases. To manifest your applications for Windows 8.1 or Windows 10, refer to Targeting your application for Windows.

This change could cause problems, so I replaced the function in commit 1509f15 (PR #46).

**Comment by tim-lebedkov** [comment]
I doubt Microsoft will remove GetVersionEx in the next years. GetFileVersionInfoSize(L"Kernel32.dll",...) seems to be even more fragile. Npackd already has a manifest (https://github.com/tim-lebedkov/npackd-cpp/blob/master/npackdg/src/npackdg.manifest) that shows that it knows about Windows 10 and GetVersionEx works properly.

**Comment by OgreTransporter** [comment]
> I doubt Microsoft will remove GetVersionEx in the next years. GetFileVersionInfoSize(L"Kernel32.dll",...) seems to be even more fragile.

That's why I replaced GetVersionEx - even if it still works sometimes.

By the way, GetVersionEx in npacked prints the following:

```
dwOSVersionInfoSize = 276
dwMajorVersion = 6
dwMinorVersion = 2
dwBuildNumber = 9200
dwPlatformId = 2
```

Correct would be `dwMajorVersion = 10` and `dwMinorVersion = 0`! Obviously, this does not always work correctly with manifest or the manifest is not properly integrated via CMake.

**Comment by OgreTransporter** [comment]
Fixed in 0c3714d. Visual Studio had ignored the manifest settings and had written its own manifest.

**Comment by tim-lebedkov** [comment]
Please create a new pull request with CMake changes only where everything builds.

**Comment by OgreTransporter** [comment]
PR #49

**Comment by OgreTransporter** [comment]
> Please create a new pull request with CMake changes only where everything builds.

PR #51
