### ISSUE TITLE
Wrong help text

### ISSUE THREAD

**Issue by OgreTransporter** [tim-lebedkov/npackd-cpp#48]
The help text of npackdcl still contains ncl instead of npackdcl. See b5a7aeb

**Comment by tim-lebedkov** [comment]
"ncl" is actually a shorter, newer name

**Comment by OgreTransporter** [comment]
Yes it is. but the name of the project and the name of exe are npackdcl.

**Comment by OgreTransporter** [comment]
Fixed in 0c3714d

**Comment by tim-lebedkov** [comment]
Please create a new pull request with CMake changes only where everything builds.
