### ISSUE TITLE
Outdated DB

### ISSUE THREAD

**Issue by Ygarr** [tim-lebedkov/npackd-cpp#5]
Due to single adding is not always convenient synchronize with some internet DB like: 
- http://wiki.appvisor.org/Main_Page
- http://wikiprograms.org/

**Comment by tim-lebedkov** [comment]
actually it is possible to host another repository: https://github.com/tim-lebedkov/npackd/wiki/RepositoryHosting

Or upload multiple versions to the default repository: http://npackd.appspot.com/rep/from-file
