### ISSUE TITLE
Reconsider the process of exporting packages

### ISSUE THREAD

**Issue by WebTiger89** [tim-lebedkov/npackd-cpp#52]
I'm a simple user but a developer as well and it took me serveral hours to determine how I can make use of these Repo.xml files. Why so complicated.

As an average user I would expect an option to export (for example) all installed apps to a file (let it be a json or xml or whatever) which later on I can import and all packages get installed.

Similar to `pip freeze > requirements.txt`

To be more concrete: In the gui you could make a context option for a package "send to export list" and a new tab would open. So the user looks for his apps he wants to install and sends one by one to this list and after he finishes he can export to a file.

Now lets assume he breaks his system by accident. He has the exported file and via gui he can import it and his apps get installed.

Currently I only see the solution to write a script by hand which performs ncl add -p=xy; ncl add -p=xy; ncl add -p=xy

or 

Select an app in the gui and export it to Repo.xml. But you still have to collect your apps by hand and write them into this file by hand.

That sucks. Npackd has a solid base, how can you miss such a basic and important feature "in a proper way".

**Comment by tim-lebedkov** [comment]
There is already an "Export" action available in the GUI.

**Comment by WebTiger89** [comment]
Yes I know and it sucks. See first paragraph.

**Comment by tim-lebedkov** [comment]
Here is how it can be accomplished: click on the radio button "Installed", press Ctrl+A to select all packages, choose "Export" from the local menu. Did you miss that you can select multiple rows in the table?
