### ISSUE TITLE
need help: transform npackd into a portable app

### ISSUE THREAD

**Issue by the-liquid-metal** [tim-lebedkov/npackd-cpp#55]
Hello.

I know this is a bit odd topic, but why not. I am still investigating how difficult that is. In my opinion, npackd is the simplest windows package manager after PortableApps.com. The ultimate goal is: manage any apps istalled in portable apps intallation directory which are not registered in PortableApps.com. The first logical step is to transform npackd into a portable app, and place it into portable apps intallation directory. Don't worry, this will not change the way the original app works, and i will not ask specific feature if not very needed.

I have difficulty recognizing each file/folder used/created by npackd and their role. Can you list them all?

nb: Please keep this thread open until the goal is reached.

**Comment by tim-lebedkov** [comment]
Wouldn't it be much easier to just ask PortableApps.com to include additional applications?

**Comment by the-liquid-metal** [comment]
Both PortableApps.com or the original vendor have their own policies whether an app can be transformed (or permitted) into a portable app or not. Many apps have been porposed for inclusion, but only a small portion is realized. Some of its even already transformed but never registered in their website (or package manager).

**Comment by tim-lebedkov** [comment]
And there is no way to have your own repository of portable apps?

**Comment by tim-lebedkov** [comment]
Npackd stores data in %ALLUSERSPROFILE%\Npackd and in the registry under HKEY_LOCAL_MACHINE\SOFTWARE\Npackd and HKEY_CURRENT_USER\SOFTWARE\Npackd. Also for detected packages it uses C:\Program Files\NpackdDetected and creates ".Npackd" sub-directories under existing software installations.

**Comment by the-liquid-metal** [comment]
> And there is no way to have your own repository of portable apps?

For me, to contribute is OK, but to create my own repo and maintain it for a long time surely not OK.
The last one is the last option to be chosen if there are no package managers suitable for me.

I don't use portable app in an ordinary way, which is to provide exactly same apps and their settings across different machines. For me, portable app is ideal environment in order to avoid virtualization. Virtualization is too overkill to be done just for trying and experimenting new apps. Let the OS be dirty, and i will reinstall it whenever i need. I just need half an hour or more to do it, and i don't have to reinstall dozens app already stable and ready to use.
