### ISSUE TITLE
Clicking Update for a package offers to uninstall unrelated packages

### ISSUE THREAD

**Issue by binki** [tim-lebedkov/npackd-cpp#6]
![offers to uninstall Blender 64 bit 2.78.3 and Audacity 2.1 when upgrading Putty from 0.67 to 0.69](http://i.imgur.com/oZxVtSo.png)

If I first open npacked, choose Updateable packages, wait for the package list refresh to finish, and then click Update, npackd-1.22.2 decides that updating my package involves uninstalling two unrelated packages. This doesn’t seem to happen if I’ve installed those packages while npackd is open. But if the first action I perform with npackd is to update some package, it’ll want to uninstall the other packages.

In my case, the package I am trying to update seems to be anything. E.g., Putty from 0.67 to 0.69 is able to trigger it. And the packages it chooses to uninstall are Audacity 2.1 and Blender 64 bit 2.78.3 (which both have names starting near the beginning of the alphabet, hmmmm…).

I can’t think of any reason for npackd to want to uninstall these packages. I want to keep them installed. I even installed them through npackd in the first place.

**Comment by tim-lebedkov** [comment]
A workaround would be probably to install "Npackd Installer Helper" first. Somehow it was deleted.

**Comment by binki** [comment]
Every time when I open npackd, it removes Npackd Installer Helper from the list of installed programs as soon as it finishes syncing with the repository.

However, that seems to be unrelated to my issue. npackd still wants to uninstall Blender and Audacity even if I use this procedure:

1. Open npackd.
2. Wait for package repo sync to finish.
3. Select and Install Npackd Installer Helper
4. Select and click Update for Putty (but I don’t click OK because I know it’ll uninstall Blender and Audacity and then I have to reinstall them. I’ve done that once before when updating another package and was hoping this could be fixed in npackd).

![updating PuTTY attempts to uninstall Audacity and Blender](http://i.imgur.com/YtjQAI4.png)

**Comment by tim-lebedkov** [comment]
please install "Npackd Installer Helper" again and post here the installation path. Maybe your Antivirus deletes the directory right after the installation? If the directory is still there, maybe something else is installed or detected in the parent directory? If this is the case, please use another installation directory (e.g. "C:\Program Files" instead of "C:\Program Files (x86)") or remove the other package somehow.

**Comment by binki** [comment]
npackd says that it installed it to `C:\Program Files\Npackd_Installer_Helper-1.22_6`.

The total list of folders under Program Files matching `Npackd*` is:

```
C:\Program Files>DIR /B Npackd*
NpackdCL
NpackdDetected
Npackd_64_bit
Npackd_Installer_Helper
Npackd_Installer_Helper-1.21
Npackd_Installer_Helper-1.21_2
Npackd_Installer_Helper-1.21_3
Npackd_Installer_Helper-1.21_4
Npackd_Installer_Helper-1.21_5
Npackd_Installer_Helper-1.21_6
Npackd_Installer_Helper-1.21_7
Npackd_Installer_Helper-1.22
Npackd_Installer_Helper-1.22_2
Npackd_Installer_Helper-1.22_3
Npackd_Installer_Helper-1.22_4
Npackd_Installer_Helper-1.22_5
Npackd_Installer_Helper-1.22_6
.NpackdTrash
```

It appears to me that `Npackd_Installer_Helper-1.22_5` has the same number of files in it as `Npackd_Installer_Helper-1.22_6`. I am using whatever antivirus is built into Windows.

I still don’t think that the issue with npackd wanting to uninstall unrelated packages (Blender Audacity) has to do with it being unable to find the already-installed Npackd_Installer_Helper. It still wants to uninstall those packages even when it thinks the installer helper is installed.

When I try to save the settings leaving it as `C:\Program Files`, Npackd tells me:

> Cannot change the installation directory to C:\Program Files. Runtime x64 for Power Manager (msi.ce244a49-26ae-4d3a-bc54-d76bcffdbea2) 1 is installed there

I also get the same error message when creating an empty directory `C:\NpackdProgramFiles` and pointing the Installation Directory setting there. I suspect that this detected MSI is just installed to `\` or something.

How do I fix this? Power Manager is a Lenovo-provided thing which I think WU installed automatically because this is a Thinkpad T540p. When I click Uninstall in Npackd, Npackd says it would have to update itself or something. I think that means that npackd realizes that it is installed to a directory that is a descendant of `C:\`. I can’t find the program listed in Programs and Features. I think even if I remove it it would end up being reinstalled automatically by WU to the same directory again.

**Comment by tim-lebedkov** [comment]
This seems to be a bug in Npackd. I don't see a workaround other than uninstalling Power Manager. I will probably create an Npackd 1.22.3 with a bugfix. Before I do this, could you please confirm that Npackd shows the installation directory of Power Manager as "C:\"?

**Comment by binki** [comment]
Oops, I didn’t think to do that. It does show up as `C:`. Here you go:

![image](https://user-images.githubusercontent.com/82626/27040210-54f67ba2-4f5e-11e7-8c5b-26df97417c0e.png)

**Comment by tim-lebedkov** [comment]
thank you

**Comment by tim-lebedkov** [comment]
Can you please test this one: https://ci.appveyor.com/project/tim-lebedkov/npackd-cpp/build/job/bfi7lr3v08jdkn5k/artifacts

**Comment by binki** [comment]
I downloaded the .zip, extracted it, and ran it straight from that folder. Then I waited for the repository refresh to complete. Then I checked for the Runtime x64 for Power Manager. Finally, I selected Putty and chose “Update”. Then I hit cancel. I also tried closing npackd and relaunching the extracted files. The results:

That version still shows Runtime x64 for Power Manager as being installed to `C:`.

When I click Update on Putty I still get the same behavior:

```
1 package(s) will be updated:
Putty 0.67 -> 0.69

2 package(s) will be uninstalled:
Blender 64 bit 2.78.3
Audacity 2.1

1 package(s) will be installed:
Npackd Installer Helper 1.22
```

Please let me know if I missed something or if you have more you want me to try.

Thanks!

**Comment by tim-lebedkov** [comment]
can you 
- start regedt32.exe, 
- delete HKEY_LOCAL_MACHINE\SOFTWARE\Npackd\Npackd\Packages\msi.ce244a49-26ae-4d3a-bc54-d76bcffdbea2-1
- start Npackd (the new one from my previous post)

**Comment by binki** [comment]
Interesting. After doing that, npackd sees the x64 and x86 versions of Runtime for Power Manager as living in `C:\Program Files\NpackdDetected\Runtime_x64_for_Power_Manager` and `C:\Program Files\NpackdDetected\Runtime_x86_for_Power_Manager-1`, respectively.

However, if I go to update PuTTY, I still get:

```
1 package(s) will be updated:
Putty 0.67 -> 0.69

2 package(s) will be uninstalled:
Blender 64 bit 2.78.3
Audacity 2.1

1 package(s) will be installed:
Npackd Installer Helper 1.22
```

I still find it strange that npackd wants to uninstall unrelated packages when I indicate I want to update Putty. I also don’t get how the installer helper not being installed is related to that.

If I install the Npackd Installer Helper and then try to update putty, I get:

```
1 package(s) will be updated:
Putty 0.67 -> 0.69

2 package(s) will be uninstalled:
Blender 64 bit 2.78.3
Audacity 2.1
```

If I restart Npackd after installing the Installer Helper, Npackd now properly detects the installed Installer Helper. So your fix does address the Lenovo Power Manager thing. But that seems to be an unrelated issue. And it would be nice if Npackd could know to recover from the situation without requiring registry editing ;-).

What should I try next? I haven’t tried uninstalling and reinstalling Blender and Audacity, should I try that to see if that fixes the issue where Npackd wants to uninstall them when updating Putty? I’m leaving things until I hear from you in case you want me to test something on my currently broken setup first…

**Comment by tim-lebedkov** [comment]
Npackd tries to repair your installed packages. Most likely not all dependencies of Blender and Audacity are installed.

You can uninstall and install Blender and Audacity. This will repair the dependencies.

**Comment by binki** [comment]
When I reinstalled Audacity, it caused LAME to be reinstalled. For Blender, it installed a Visual C++ redistributable. It seems that with your fix, npackd now remembers that their deps are installed when I reopen it, so it no longer tries to uninstall those when I update packages.

Thanks for the help! Now I just have to remember to use the npackd version from the build artifacts instead of the latest release.

**Comment by stonecrusher** [comment]
Same problem here:
Right click on `MusicBrainz Picard` to update only that one, but npackd additionally wants to install an outdated Visual C++ package and uninstall unrelated programs which all work fine.
![npackd](https://user-images.githubusercontent.com/1388389/54126170-38ce1300-4407-11e9-8863-6178e28b3206.png)

**Comment by tim-lebedkov** [comment]
@stonecrusher try to install "MyUninstaller" again. This dependency is probably missing in your installation. You can also try the next (yet unstable) version: https://ci.appveyor.com/project/tim-lebedkov/npackd-cpp/build/job/odt489fmy4uuqaor/artifacts
It handles these situations differently.

**Comment by stonecrusher** [comment]
I never installed "MyUninstaller" before, just the Npackd64-1.24.8.msi.
After installing MyUninstaller, the same problem occured, just with XAMPP missing from the packets to be falsely uninstalled.
Trying to uninstall MyUninstaller resulted in additional 6 packets to be removed.

The new version 1.2.5 works better. It doesn't want to uninstall stuff now, but install more than wanted:
- `Npackd Installer Helper 1.22` (mhm, ok. Shouldn't that be included in the main installer?)
- `Lame for Audacity 3.99.3` (a dependency not compulsory and already installed)
- `Visual C++ redistributable package 9.0.30729.4148` although a newer version of that redist is already installed

Looks like we have a little dependency mess here.

**Comment by tim-lebedkov** [comment]
MyUninstaller [1.74, 2) is a dependency of your XAMPP 7.3. It was installed previously, but was probably removed either via the control panel or even maybe by an AntiVirus. So please leave MyUninstaller there.

Npackd 1.25 solves missing dependencies by installing packages. Npackd 1.24 did this by removing them.

There are advantages and disadvantages in having "Npackd Installer Helper". If you really think it should be in Npackd, please file another issue.

Lame for Audacity is a dependency of "Exact Audio Copy". This is also OK.

Visual C++ redistributable is unfortunately not detected. I will look into this.

**Comment by tim-lebedkov** [comment]
Interestingly my installation on Windows 10 detects "Visual Studio C++ redistributable 9.0.30729.4148" without any problems.

**Comment by tim-lebedkov** [comment]
which packages does Npackd find if you search for "visual studio c++ 2008 redistributable i686"?

**Comment by stonecrusher** [comment]
> MyUninstaller [1.74, 2) is a dependency of your XAMPP 7.3. It was installed previously, but was probably removed either via the control panel or even maybe by an AntiVirus.

Strange. I don't remember having removed it manually and avast never did anything like this before.

> Lame for Audacity is a dependency of "Exact Audio Copy". This is also OK.

But it is already installed. Probably not via npackd.
![2019-03-12 23_35_12-Lame For Audacity](https://user-images.githubusercontent.com/1388389/54241379-fe589900-4520-11e9-8b01-2eed4d8eba1e.png)

> Interestingly my installation on Windows 10 detects "Visual Studio C++ redistributable 9.0.30729.4148" without any problems.

Hmm, got Win8.1 here with the newer `Visual Studio C++ redistributable 9.0.30729.7523` as seen [here](https://github.com/tim-lebedkov/npackd-cpp/issues/6#issuecomment-471533365).

> which packages does Npackd find if you search for "visual studio c++ 2008 redistributable i686"?

Only this one:
![2019-03-13 00_47_50-Npackd](https://user-images.githubusercontent.com/1388389/54243688-be49e400-4529-11e9-8430-2e394b864283.png)

**Comment by tim-lebedkov** [comment]
It's pretty hard to diagnose something like this remotely. Please install NpackdCL 1.24.8, open the command line and execute the following:

`"C:\Program Files\NpackdCL\ncl" search --json>Packages.txt`

The upload the "Packages.txt" file here.

**Comment by stonecrusher** [comment]
Here it is: [Packages.txt](https://github.com/tim-lebedkov/npackd-cpp/files/2968388/Packages.txt)

**Comment by tim-lebedkov** [comment]
please open the command line and execute the following as administrator:

`"C:\Program Files\NpackdCL\ncl" detect -d>Log.txt
`
Then upload the "Log.txt" file here.

**Comment by stonecrusher** [comment]
This command took surprisingly long, but here's the result: [Log.txt](https://github.com/tim-lebedkov/npackd-cpp/files/2968585/Log.txt)

**Comment by tim-lebedkov** [comment]
sorry, the command should have been this. Please upload the new Log.txt.

`"C:\Program Files\NpackdCL\ncl" detect -d>Log.txt 2>&1`

**Comment by stonecrusher** [comment]
No problem, happy to help / find possible bug. [Log2.txt](https://github.com/tim-lebedkov/npackd-cpp/files/2968639/Log2.txt)

**Comment by tim-lebedkov** [comment]
One idea I have now is that "Microsoft Visual C++ 2008 Redistributable - x86 9.0.30729.7523" is indeed not installed. What happens if you try to uninstall it via "Programme und Features"?

**Comment by stonecrusher** [comment]
It's been installed and got removed successfully by Windows Installer.

/edit
Reinstalled it from [here](https://www.microsoft.com/de-de/download/confirmation.aspx?id=5582). Now in "Programs and features" the build number (last four digits) is missing (compare to x64 version), but npackd still wants to install its own version `x86 9.0.30729.4148` when trying to update Picard.
![2019-03-15 21_22_43-Programme und Features](https://user-images.githubusercontent.com/1388389/54460063-c17ee300-4768-11e9-9065-17d15df3414c.png)
Looks like an issue of sanitizing/comparing version numbers?

**Comment by tim-lebedkov** [comment]
Could you please try this version: https://ci.appveyor.com/project/tim-lebedkov/npackd-cpp/build/job/5mwexmv5ducgnaat/artifacts ?

**Comment by stonecrusher** [comment]
It doesn't erroneosly want to update the c++ 2008 redist anymore. :+1: 
Though, when trying to update Picard, it still sees it as missing dependency.
![2019-03-19 22_49_37-Greenshot](https://user-images.githubusercontent.com/1388389/54644676-2785a600-4a9a-11e9-96b8-e861c3c97500.png)

**Comment by tim-lebedkov** [comment]
Picard had a strange dependency on exact this version of "Visual C++ redistributable". Please try again.

**Comment by stonecrusher** [comment]
The C++ redist problem looks solved!
I now recognized another pattern: Every package I want to update wants to install `npackd installer helper 1.22` and `Lame for Audacity 3.99.3`. Also recognize the text below that has to be changed from uninstalling to installing dependencies.
![2019-03-21 20_51_02-Installieren_Deinstallieren](https://user-images.githubusercontent.com/1388389/54780893-3ba4e100-4c1b-11e9-9caf-8babfcdf8d64.png)

**Comment by tim-lebedkov** [comment]
"Npackd Installer Helper" cannot be detected at all. "Lame for Audacity" is not in your "Add or remove software" control panel. This means it cannot be installed also.

=> just click "OK" and install 2 dependencies

**Comment by stonecrusher** [comment]
Looks good to me now! Might be closed again.
I'll open new issues for some specific detection problems on programs not installed via npackd before.

**Comment by tim-lebedkov** [comment]
great!
