### ISSUE TITLE
Darktable and KDE Connect

### ISSUE THREAD

**Issue by Mannshoch** [tim-lebedkov/npackd-cpp#60]
Please add 
https://github.com/darktable-org/darktable/releases/
and 
https://binary-factory.kde.org/job/kdeconnect-kde_Release_win64/ to your repository.
My old Darktable and Kdeconnect got no update from npackd

**Comment by tim-lebedkov** [comment]
Please use https://www.npackd.org/package/new to propose new packages

**Comment by Mannshoch** [comment]
Sorry, but I do not have a Google account
