### ISSUE TITLE
how to avoid creating .npackd directory in program files?

### ISSUE THREAD

**Issue by Mannshoch** [tim-lebedkov/npackd-cpp#61]
I removed some Apps from Windows "Apps and features" the uninstaller got error because of some files not related to this app. After that I detected in many folders from uninstalled apps which remained because their only content is an .npackd directory.

**Comment by Mannshoch** [comment]
By the way. That leftover directories have nothing to do with application I manage with npackd

**Comment by tim-lebedkov** [comment]
Even if you didn't install an application via Npackd, it gets detected and a sub-directory named ".Npackd" is created. At least an uninstall script is placed there. There are probably very few applications that fail to uninstall because of this. Which applications were this exactly?

**Comment by Mannshoch** [comment]
It was a preinstalled ASUS app which was originally designed for Windows 8.1. (I cleaned an old Laptop)
Why do you need to place files into the same directory like the installed app? Couldn't you just save this information into npackd's own directory?
I would prefer to only manage applications with npackd which I could also refresh to a newer version with npackd.
I detect that c:\program files Is polluted by leftover directories from earlier uninstallations which only contain .npackd directories.

**Comment by tim-lebedkov** [comment]
The scripts in an .Npackd sub-directory are used to uninstall a package. Any package can have these files. If a package is detected, the files are created e.g. from an entry in the Windows registry. I guess it could be possible to place the files somewhere else and only copy them into the right directory during an un-installation, but it would make the whole program more complicated unnecessary. You can just delete the directories.

The idea is to detect and manage all installed programs (.msi, .exe, etc) in one place.

**Comment by tim-lebedkov** [comment]
BTW, if you would use Npackd to uninstall those applications, the .Npackd directories would be deleted automatically.

**Comment by Mannshoch** [comment]
I do not plan using .npackd as main installer/uninstaller.
Goal is using npackd only for updates on by npackd updatable software. At moment, I'm not able to give this tool not computer interested user for their own use.
