### ISSUE TITLE
Installation does not work when version is specified in the update command.

### ISSUE THREAD

**Issue by teionn** [tim-lebedkov/npackd-cpp#62]
If the version is specified when executing the update command, the process will be completed with the message "The packages are already up-to-date" regardless of whether the package is installed or not.

Result when Blender64 is not installed

`npackdcl update --package Blender64 --versions 2.90 -i`

```
[0%] - Updating packages
The packages are already up-to-date
```

**Comment by tim-lebedkov** [comment]
What exactly is your expectation for this command? What should it do?

**Comment by tim-lebedkov** [comment]
There is actually an error in the command line. --versions should be a range of versions like "[2, 3)". This error is not handled correctly. That's why you don't get a proper error message.

**Comment by teionn** [comment]
I'm sorry.
I wrote the code incorrectly.

After writing it correctly, I was able to install it.

I have one question: "[2, 3)" In this case, 2 is installed, but what does the 3 on the right mean?

**Comment by tim-lebedkov** [comment]
npackdcl update --package Blender64 --versions "[2,3)" -i

means "update or install the newest version of Blender not older than 2 and not newer or equal to 3".

If you just want to update Blender, the following command is enough:
npackdcl update --package Blender64
