### ISSUE TITLE
Scripts terminate with "unresolved dependencies..."

### ISSUE THREAD

**Issue by skahde** [tim-lebedkov/npackd-cpp#67]
"Nicht aufgelöste Abhängigkeit: com.microsoft.Windows32 [1, 1000)" (german language Windows 10)

This issue obviously affects alle attempts to install or uninstall. As examples I used the ones that are due for an update and all are affected.

![grafik](https://user-images.githubusercontent.com/102651437/162185453-6bf84218-3fa0-45db-9c83-155025092ae5.png)

Windows-Versions in use:

![grafik](https://user-images.githubusercontent.com/102651437/162185115-70563552-2a98-4979-acd0-f71a2a2b2f54.png)

Many thanks in advance for any hints to a solution!

**Comment by tim-lebedkov** [comment]
Try "Package/Check dependencies".

**Comment by tim-lebedkov** [comment]
let me reopen this. We could make some improvements here.

**Comment by sonofevil** [comment]
I also have this issue. I'm also located in Germany but using English Windows 10.

**Comment by tim-lebedkov** [comment]
@sonofevil what exactly does "Package/Check dependencies" say?

**Comment by sonofevil** [comment]
> @sonofevil what exactly does "Package/Check dependencies" say?

When checking dependencies: `Kodi (kodi) 19.4 depends on com.microsoft.Windows32 (com.microsoft.Windows32) [1, 1000), which is not installed`
When trying to install an app: `Unsatisfied dependency: com.microsoft.Windows32 [1, 1000)`

**Comment by tim-lebedkov** [comment]
@sonofevil I removed the dependency on 32 bit Windows from Kodi 19.4. You should now be able to install other packages.

**Comment by tim-lebedkov** [comment]
duplicates #66
