### ISSUE TITLE
Visual Studio Code is uninstalled on my machine but is still listed as installed in Npackd

### ISSUE THREAD

**Issue by achangofpace** [tim-lebedkov/npackd-cpp#68]
![image](https://github.com/npackd/npackd/assets/55330719/acf2f926-651e-4928-a567-ae9b96c1d7b7)

![image](https://github.com/npackd/npackd/assets/55330719/abdafe4c-f23b-4e8e-aa4a-5465f9ba98b8)

When I try to uninstall it using the GUI, I get the following error

![image](https://github.com/npackd/npackd/assets/55330719/9be23694-bef3-4a5a-b96f-7972b6ca2c3b)

Here's the only contents of the directory referenced in the error message:
![image](https://github.com/npackd/npackd/assets/55330719/d9255687-5d2b-4ea9-b0a2-bfd2d561f989)

This same issue is happening for ImageGlass too

**Comment by tim-lebedkov** [comment]
The package version is probably detected somehow. Please double click on the package in the table and then double click on the installed version. What is shown in the text field named "Detection info"?

**Comment by achangofpace** [comment]
For VS Code: 
![image](https://github.com/npackd/npackd/assets/55330719/89ff8b35-0ddb-4636-935f-bae3bb69d6c7)

control-panel:HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{EA457B21-F73E-494C-ACAB-524FDE069978}_is1

For ImageGlass:
![image](https://github.com/npackd/npackd/assets/55330719/589b5488-d35b-4e2a-a90c-a9c344dde326)

msi:{ff4ea68e-4cb5-44bf-82b8-48aad9b89ea3}

**Comment by tim-lebedkov** [comment]
Looks like the VSCode uninstaller has some leftovers in the registry. You can delete HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall{EA457B21-F73E-494C-ACAB-524FDE069978}_is1

Npackd should show the program as not installed after this.

For ImageGlass you could use "msiexec.exe" to uninstall using the GUID {ff4ea68e-4cb5-44bf-82b8-48aad9b89ea3}.

**Comment by achangofpace** [comment]
I'm not finding the VSCode key in my registry
![image](https://github.com/npackd/npackd/assets/55330719/43862365-2964-4256-b4c5-32baaea0142c)

and

> msiexec.exe /x {ff4ea68e-4cb5-44bf-82b8-48aad9b89ea3}

pops up a window that says "This action is only valid for products that are currently installed"

the log says:

> === Verbose logging started: 10/23/2023  13:32:47  Build type: SHIP UNICODE 5.00.10011.00  Calling process: C:\Windows\system32\msiexec.exe ===
> MSI (c) (AC:F4) [13:32:47:468]: Font created.  Charset: Req=0, Ret=0, Font: Req=MS Shell Dlg, Ret=MS Shell Dlg
> 
> MSI (c) (AC:F4) [13:32:47:468]: Font created.  Charset: Req=0, Ret=0, Font: Req=MS Shell Dlg, Ret=MS Shell Dlg
> 
> MSI (c) (AC:04) [13:32:47:486]: Resetting cached policy values
> MSI (c) (AC:04) [13:32:47:486]: Machine policy value 'Debug' is 0
> MSI (c) (AC:04) [13:32:47:486]: ******* RunEngine:
>            ******* Product: {ff4ea68e-4cb5-44bf-82b8-48aad9b89ea3}
>            ******* Action: 
>            ******* CommandLine: **********
> MSI (c) (AC:04) [13:32:47:487]: Client-side and UI is none or basic: Running entire install on the server.
> MSI (c) (AC:04) [13:32:47:487]: Grabbed execution mutex.
> MSI (c) (AC:04) [13:32:47:520]: Cloaking enabled.
> MSI (c) (AC:04) [13:32:47:520]: Attempting to enable all disabled privileges before calling Install on Server
> MSI (c) (AC:04) [13:32:47:523]: Incrementing counter to disable shutdown. Counter after increment: 0
> MSI (s) (C4:08) [13:32:47:533]: Running installation inside multi-package transaction {ff4ea68e-4cb5-44bf-82b8-48aad9b89ea3}
> MSI (s) (C4:08) [13:32:47:533]: Grabbed execution mutex.
> MSI (s) (C4:D0) [13:32:47:535]: Resetting cached policy values
> MSI (s) (C4:D0) [13:32:47:535]: Machine policy value 'Debug' is 0
> MSI (s) (C4:D0) [13:32:47:535]: ******* RunEngine:
>            ******* Product: {ff4ea68e-4cb5-44bf-82b8-48aad9b89ea3}
>            ******* Action: 
>            ******* CommandLine: **********
> MSI (s) (C4:D0) [13:32:47:535]: Machine policy value 'DisableUserInstalls' is 0
> MSI (s) (C4:D0) [13:32:47:535]: MainEngineThread is returning 1605
> MSI (s) (C4:08) [13:32:47:536]: User policy value 'DisableRollback' is 0
> MSI (s) (C4:08) [13:32:47:536]: Machine policy value 'DisableRollback' is 0
> MSI (s) (C4:08) [13:32:47:536]: Incrementing counter to disable shutdown. Counter after increment: 0
> MSI (s) (C4:08) [13:32:47:536]: Note: 1: 1402 2: HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Installer\Rollback\Scripts 3: 2 
> MSI (s) (C4:08) [13:32:47:538]: Note: 1: 1402 2: HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Installer\Rollback\Scripts 3: 2 
> MSI (s) (C4:08) [13:32:47:539]: Decrementing counter to disable shutdown. If counter >= 0, shutdown will be denied.  Counter after decrement: -1
> MSI (c) (AC:04) [13:32:47:540]: Decrementing counter to disable shutdown. If counter >= 0, shutdown will be denied.  Counter after decrement: -1
> MSI (c) (AC:04) [13:32:47:542]: MainEngineThread is returning 1605
> === Verbose logging stopped: 10/23/2023  13:32:47 ===

**Comment by tim-lebedkov** [comment]
I was able to reproduce with ImageGlass:
- install it via an .msi
- start Npackd and remove it via Npackd
- F5
=> the program is still in the list as "installed"

**Comment by achangofpace** [comment]
Do you think if I uninstalled Npackd and reinstalled it, it might fix it? I'll have to find a machine to test this on.

**Comment by tim-lebedkov** [comment]
No, reinstalling Npackd will not fix this. 

Strangely enough in "Add/Remove Programs" ImageGlass is still present and can be uninstalled.

You will probably have to wait for the next version for this to be fixed.

**Comment by tim-lebedkov** [comment]
Wait a second, your case is different:

- install it via an .msi
- start Npackd, close Npackd
- remote it via "Control panel"
- start Npackd
=> the program is still in the list as "installed"

**Comment by tim-lebedkov** [comment]
It helped to just delete the "NpackdDetected\ImageGlass" directory in my case. Could you please try to do the same?

**Comment by achangofpace** [comment]
Ah that did it for ImageGlass! I actually did have the same case where I tried to uninstall it with Npackd first and then did it with control panel.

**Comment by achangofpace** [comment]
I just deleted the Visual_Studio_Code folder in the same directory and that worked too! Thanks for helping with this.

I could have sworn I tried something like this before opening the issue? oh well

**Comment by tim-lebedkov** [comment]
fixed for 1.27
