### ISSUE TITLE
Allow commenting out repositories in the config dialog

### ISSUE THREAD

**Issue by nodiscc** [tim-lebedkov/npackd-cpp#7]
Currently there is no way to tell Npackd to ignore an entry in the repository list (other than removing it's line altogether). It would be nice to be able to disable a repository by adding `#` (or another character) in front of it's entry).

I have a computer without initial network connectivity. To be able to use my local repository (added the `file:///...` URI to my `Rep.xml` file), I had to remove the default entries `http://npackd.appspot.com/rep/xml?tag=stable/stable64` since the repository update would fail without an internet connection, leaving me with an empty package list. Re-adding the default repos at a later time required manually copying the address from the website. It would be simpler to just comment/uncomment them.

Alternatively the repository update could just throw a warning when some repos are unavailable, and still process repos that can be reached (eg. local)

**Comment by tim-lebedkov** [comment]
it seems that at least a button "add default repositories" should be there

**Comment by tim-lebedkov** [comment]
how about a dropdown with the list of previously used repositories? BTW, you know that you can change the list of repositories via ncl.exe, right?

**Comment by tim-lebedkov** [comment]
Here is the current screenshot:

![settings](https://user-images.githubusercontent.com/831371/28062398-13170530-662e-11e7-9abf-80585f5d924c.png)

**Comment by nodiscc** [comment]
> a dropdown with the list of previously used repositories
> current screenshot

Yes, this is nice. I think the dropdown list should list the stable/stable64/libs/unstable repo URLs by default (in addition to the recently used URIs). Thanks!

**Comment by tim-lebedkov** [comment]
Here is how it will look in 1.24:

![settings](https://user-images.githubusercontent.com/831371/35070771-b50ce5a8-fbde-11e7-8fc5-54a166e038c1.png)

**Comment by OgreTransporter** [comment]
It's working well
